### ISSUE TITLE
Error response from daemon: driver failed programming external connectivity on endpoint docksal-vhost-proxy 

### ISSUE THREAD

**Issue by sean-e-dietrich** [docksal/docksal#482]
**Description**

**Steps to reproduce the issue:**

1. type `fin status` or `fin start` in any project

**Describe the results you received:**

Getting the following error message

```
fin start
 ALERT:  Some Docksal services were not running
         Restarting Docksal system services...
Resetting network settings...
Resetting Docksal services...
 * proxy
docker: Error response from daemon: driver failed programming external connectivity on endpoint docksal-vhost-proxy (0d18d6c321fd006ac0dc94620aa80de9f826e2366363a9c818ced82bfc5320b6): Error starting userland proxy: listen tcp 192.168.64.100:443: bind: cannot assign requested address.
 * dns and resolver for .docksal domain
docker: Error response from daemon: driver failed programming external connectivity on endpoint docksal-dns (8083a6c34650b86943e4ae7eb022fc08558602d0c369f7496b5f2fa720d07af5): Error starting userland proxy: listen udp 192.168.64.100:53: bind: cannot assign requested address.
Enabling automatic *.docksal DNS resolver...
Clearing DNS cache...
 * ssh-agent
Identity added: id_rsa (id_rsa)
Starting services...
Starting wisconsinprivatecolleges_db_1 ...
Starting wisconsinprivatecolleges_cli_1 ...
Starting wisconsinprivatecolleges_cli_1 ... done
Starting wisconsinprivatecolleges_web_1 ... done
Waiting for wisconsinprivatecolleges_cli_1 to become ready...
Connected vhost-proxy to "wisconsinprivatecolleges_default" network.
Virtual Host: wisconsinprivatecolleges.docksal
```

**Describe the results you expected:**

Would assume the project would be starting. 

**Output of `fin config`:**

<details>
  <summary>fin config output</summary>

```
[101m ALERT: [0m [0;91mSome Docksal services were not running[0m
         Restarting Docksal system services...
[0;32mResetting network settings...[0m
[0;32mResetting Docksal services...[0m
 * proxy
 * dns and resolver for .docksal domain
[0;32mEnabling automatic *.docksal DNS resolver...[0m
[0;32mClearing DNS cache...[0m
 * ssh-agent
Identity added: id_rsa (id_rsa)
---------------------
COMPOSE_PROJECT_NAME_SAFE: wisconsinprivatecolleges
COMPOSE_FILE:
/Users/nikki/.docksal/stacks/volumes-bind.yml
/Users/nikki/docksal/wisconsin-private-colleges/.docksal/docksal.yml
ENV_FILE:
/Users/nikki/docksal/wisconsin-private-colleges/.docksal/docksal.env

PROJECT_ROOT: /Users/nikki/docksal/wisconsin-private-colleges
DOCROOT: .
VIRTUAL_HOST: wisconsinprivatecolleges.docksal
VIRTUAL_HOST_ALIASES: *.wisconsinprivatecolleges.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32768

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      DOCROOT: .
      HOST_GID: '20'
      HOST_UID: '501'
      LANG: en_US.UTF-8
      LANGUAGE: en_US.UTF-8
      LC_ALL: en_US.UTF-8
      VIRTUAL_HOST: wisconsinprivatecolleges.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:1.3-php5
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - /Users/nikki/docksal/wisconsin-private-colleges/.docksal/etc/drush:/etc/drush:ro
    - /home/docker
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.1-mysql-5.6
    ports:
    - 3306/tcp
    volumes:
    - project_root:/var/www:ro,nocopy
  mail:
    environment:
      MH_API_BIND_ADDR: 0.0.0.0:80
      MH_UI_BIND_ADDR: 0.0.0.0:80
    expose:
    - '80'
    hostname: mail
    image: mailhog/mailhog
    labels:
      io.docksal.virtual-host: webmail.wisconsinprivatecolleges.docksal
    user: root
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/.
      APACHE_FILE_PROXY: http://www.wisconsinsprivatecolleges.org
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.project-root: /Users/nikki/docksal/wisconsin-private-colleges
      io.docksal.virtual-host: wisconsinprivatecolleges.docksal,*.wisconsinprivatecolleges.docksal
    volumes:
    - /Users/nikki/docksal/wisconsin-private-colleges/.docksal/etc/apache:/usr/local/apache2/conf/extra/includes:ro
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /Users/nikki/docksal/wisconsin-private-colleges
      o: bind
      type: none

---------------------

```

</details>

<br>

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output</summary>

  ```
███  OS
Mac OS X 10.11.6
Darwin kanopi-mbp.3521.dhcp.asu.edu 15.6.0 Darwin Kernel Version 15.6.0: Sun Jun  4 21:43:07 PDT 2017; root:xnu-3248.70.3~1/RELEASE_X86_64 x86_64
Mode: VirtualBox VM

███  FIN
fin version: 1.50.3

███  ENVIRONMENT
DOCKER_HOST		| tcp://192.168.64.102:2376
[43;90m WARNING: [0m [1;33mNon-default DOCKER_HOST[0m
------------------------------------------------------------
DOCKSAL_NFS_PATH	| /Users/nikki/docksal

███  DOCKER
EXPECTED VERSION: 17.09.0-ce

Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: false

███  DOCKER INFO
Containers: 17
 Running: 5
 Paused: 0
 Stopped: 12
Images: 9
Server Version: 17.09.0-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 142
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.89-boot2docker
Operating System: Boot2Docker 17.09.0-ce (TCL 7.2); HEAD : 06d5c35 - Wed Sep 27 23:22:43 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955GiB
Name: docksal
ID: KIKG:DCQG:PAUT:4MNL:E35B:SAJW:FLG5:ECBV:FXQS:OFHO:PBPX:BDIR
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 60
 Goroutines: 56
 System Time: 2018-03-22T20:50:51.120752221Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

███  DOCKER COMPOSE
EXPECTED VERSION: 1.19.0
docker-compose version 1.19.0, build 9e633ef
docker-py version: 2.7.0
CPython version: 2.7.10
OpenSSL version: OpenSSL 0.9.8zh 14 Jan 2016

███  DOCKER MACHINE
EXPECTED VERSION: 0.14.0
docker-machine version 0.14.0, build 89b8332

NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
docksal   *        virtualbox   Running   tcp://192.168.64.102:2376           v17.09.0-ce   

███  DOCKER: IMAGES
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
docksal/vhost-proxy   1.2                 a1c980537985        7 days ago          166MB
docksal/cli           1.3-php7            19bdddfeab89        6 months ago        759MB
docksal/cli           1.3-php5            80248f5ea845        6 months ago        814MB
docksal/web           2.1-apache2.4       32c1d32eba6d        7 months ago        87.5MB
docksal/db            1.1-mysql-5.6       6feb79af9597        8 months ago        298MB
mailhog/mailhog       latest              669347153085        11 months ago       19.1MB
docksal/dns           1.0                 20c7a535479d        14 months ago       61.6MB
docksal/ssh-agent     1.0                 148220cc033d        14 months ago       12.2MB
docksal/solr          1.0-solr3           628ee3683031        14 months ago       471MB

███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                    PORTS                        NAMES
144e72c64837        docksal/ssh-agent:1.0       "/run.sh ssh-agent"      53 seconds ago      Up 52 seconds                                          docksal-ssh-agent
a8d3cc3e15bc        docksal/web:2.1-apache2.4   "httpd-foreground"       9 minutes ago       Up 49 seconds             80/tcp, 443/tcp              wisconsinprivatecolleges_web_1
c5c4247b26c9        docksal/db:1.1-mysql-5.6    "/entrypoint.sh my..."   9 minutes ago       Up 50 seconds             0.0.0.0:32768->3306/tcp      wisconsinprivatecolleges_db_1
0402105c1420        mailhog/mailhog             "MailHog"                9 minutes ago       Up 50 seconds             80/tcp, 1025/tcp, 8025/tcp   wisconsinprivatecolleges_mail_1
7eff438454db        docksal/cli:1.3-php5        "/opt/startup.sh s..."   9 minutes ago       Up 50 seconds (healthy)   22/tcp, 9000/tcp             wisconsinprivatecolleges_cli_1

███  VIRTUALBOX
EXPECTED VERSION: 5.1.28
5.1.28r117968

███  VIRTUALBOX NETWORK INTERFACES
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.64.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

███  NFS EXPORTS

# VAGRANT-BEGIN: 501 52bdcb92-4bfa-4688-bc52-b86ff059c802
"/Users/nikki/Dropbox/work/kanopi/threshold/docroot" 192.168.85.101 -alldirs -mapall=501:20
"/Users/nikki/Dropbox/work/kanopi/threshold/drupal-vm" 192.168.85.101 -alldirs -mapall=501:20
# VAGRANT-END: 501 52bdcb92-4bfa-4688-bc52-b86ff059c802
# <ds-nfs docksal
/Users/nikki/docksal 127.0.0.1 192.168.64.102 -alldirs -maproot=0:0
# ds-nfs>

███  DOCKSAL MOUNTS
192.168.64.1:/Users/nikki/docksal on /Users/nikki/docksal type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)
192.168.64.1:/Users/nikki/docksal/wisconsin-private-colleges on /mnt/sda1/var/lib/docker/volumes/wisconsinprivatecolleges_project_root/_data type nfs (rw,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,nocto,nolock,proto=tcp,port=2049,timeo=70,retrans=3,sec=sys,local_lock=all,addr=192.168.64.1)

███  HDD Usage
Filesystem                Size      Used Available Use% Mounted on
/dev/sda1                46.3G      3.6G     40.3G   8% /mnt/sda1

███  RAM Usage
             total       used       free     shared    buffers     cached
Mem:       2050284     989992    1060292     200248      28892     298100
-/+ buffers/cache:     663000    1387284
Swap:      1423020          0    1423020

███  RAM Usage per container
CONTAINER                         CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
docksal-ssh-agent                 0.00%               640KiB / 1.955GiB     0.03%               868B / 0B           0B / 0B             2
wisconsinprivatecolleges_web_1    0.07%               2.441MiB / 1.955GiB   0.12%               1.22kB / 0B         8MB / 0B            82
wisconsinprivatecolleges_db_1     0.04%               490.7MiB / 1.955GiB   24.51%              1.31kB / 0B         31.5MB / 45.1kB     21
wisconsinprivatecolleges_mail_1   0.00%               1.629MiB / 1.955GiB   0.08%               1.31kB / 0B         8.92MB / 0B         3
wisconsinprivatecolleges_cli_1    0.02%               16.98MiB / 1.955GiB   0.85%               1.31kB / 0B         55.2MB / 8.19kB     6
  ```

</details>

**Comment by lmakarov** [comment]
@sean-e-dietrich  do you get the same error from `fin system reset`?

`sudo lsof -n -P -i :80 | grep LISTEN` ?

**Comment by sean-e-dietrich** [comment]
@lmakarov when run `fin system reset`

```
➜  wisconsin-private-colleges git:(master) ✗ fin system reset
Resetting network settings...
Password:
Resetting Docksal services...
* proxy
* dns and resolver for .docksal domain
Enabling automatic *.docksal DNS resolver...
Clearing DNS cache...
* ssh-agent
Identity added: id_rsa (id_rsa)
```

and nothing outputs when the `sudo lsof -n -P -i :80 | grep LISTEN` command is ran.

**Comment by lmakarov** [comment]
Looks like now you should have the vhost-proxy and dns services up and running. But that does not explain what caused the issue in the first place.

See if you can reproduce this by killing the system services

```
fin docker rm -f vhost-proxy
fin docker rm -f dns
```

then doing `fin status`.

If that does not trigger the same error, then you may have had another "stack" (?) binding to ports 80, 443 and 53 on a wildcard IP (`0.0.0.0`). Or maybe there was a glitch in the VirtualBox networking stack.

`sudo lsof -n -P -i :80 | grep LISTEN` would normally show what's using port 80, however, it won't show any of the VirtualBox processes/interfaces (it's a mystery to me why).

**Comment by drnikki** [comment]
Hi @lmakarov thanks for looking at this.  This is actually my system that sean has been helping me debug.  

```
➜  wisconsin-private-colleges git:(master) ✗ fin docker rm -f dns
Error response from daemon: No such container: dns
➜  wisconsin-private-colleges git:(master) ✗ fin status
Name   Command   State   Ports
------------------------------
➜  wisconsin-private-colleges git:(master) ✗
```

**Comment by lmakarov** [comment]
Hi @drnikki, my bad... these are the correct rm commands:

```
fin docker rm -f docksal-vhost-proxy
fin docker rm -f docksal-dns
```

**Comment by sean-e-dietrich** [comment]
@lmakarov I was just helping her out and realized that was the case. We ran those and then ran `fin status` and everything is all good now!

Is it possible it could have been the network causing an issue?

**Comment by lmakarov** [comment]
@sean-e-dietrich 

> Error starting userland proxy: listen tcp 192.168.64.100:443: bind: cannot assign requested address
> Error starting userland proxy: listen udp 192.168.64.100:53: bind: cannot assign requested address.

These usually mean that something is already listening on those ports, so another service cannot bind to those. In rare cases there may be issues in the VirtualBox network stack, when it does not release the ports properly, but I'm not 100% confident that was the case either.

`fin system reset` is the first thing to try to fix the Docksal system services.

**Comment by njbarrett** [comment]
Hello. I think i am having a similar issue.
Here is the output from `fin system reset`

```
Resetting network settings...
Resetting Docksal services...
 * proxy
docker: Error response from daemon: driver failed programming external connectivity on endpoint docksal-vhost-proxy (7a5b8d63544b76857aaa5df3d6a00a9bcd09dc7c3673a64fa9a1739939a0c119): Error starting userland proxy: listen tcp 192.168.64.100:443: bind: cannot assign requested address.
 * dns and resolver for .docksal domain
docker: Error response from daemon: driver failed programming external connectivity on endpoint docksal-dns (13223f73ca9c0b9f1a91215297c1883c8a74f768f1c256695134c5c2aa2b6795): Error starting userland proxy: listen udp 192.168.64.100:53: bind: cannot assign requested address.
Enabling automatic *.docksal DNS resolver...
Clearing DNS cache...
 * ssh-agent
Identity added: id_rsa (id_rsa)
```

**Comment by njbarrett** [comment]
Here's the output from `fin status`

```
Nicholass-MacBook-Pro nick$ fin status
 ALERT:  Some Docksal services were not running
         Restarting Docksal system services...
Resetting network settings...
Resetting Docksal services...
 * proxy
docker: Error response from daemon: driver failed programming external connectivity on endpoint docksal-vhost-proxy (df1fbe36a892d9260154781286e06b776bf47e55c4d6a1016556af3c3de34a41): Error starting userland proxy: listen tcp 192.168.64.100:443: bind: cannot assign requested address.
 * dns and resolver for .docksal domain
docker: Error response from daemon: driver failed programming external connectivity on endpoint docksal-dns (cbfad5318bea29747123ccd1189397ee7c84c2c99c749b68f0b253ee6dd6a8bb): Error starting userland proxy: listen udp 192.168.64.100:53: bind: cannot assign requested address.
Enabling automatic *.docksal DNS resolver...
Clearing DNS cache...
 * ssh-agent
Identity added: id_rsa (id_rsa)
Name   Command   State   Ports
------------------------------
```

**Comment by achekulaev** [comment]
@njbarrett apparently you have something listening on these ports. Try restarting your host. If the problem persists please post outputs of

1. `fin sysinfo`

2. `netstat -a -n tcp | grep -i listen`

**Comment by achekulaev** [comment]
Hey @sean-e-dietrich 
Can this one be closed?

**Comment by sean-e-dietrich** [comment]
@achekulaev yes, this is good to close. This was an issue with the network that the machine was one.

**Comment by svict4** [comment]
I'm encountering the same problem, could we reopen this issue?
Guessing it's unlikely to be an issue with Docksal specifically though.

Problem occured after PC went to sleep for the night.
I'm on WSL Ubuntu on Windows. I've turned off `fastboot` (as that seemed to be an issue with Docker when Googling a bit) and have done a restart. Ports are still in use and unsure how else to kill the program.

<details>
  <summary>fin config output</summary>

```
svict4@DESKTOP-4UL0CBL:/mnt/c/Users/email/Desktop/coding_projects/projectA$ fin config
 ALERT:  Some Docksal services were not running
         Restarting Docksal system services...
Configuring network settings...
Resetting Docksal services...
 * proxy
docker: Error response from daemon: driver failed programming external connectivity on endpoint docksal-vhost-proxy (ee3d33e32f860d9d353068d0233993a08fbb917635d1c102fae7910ebe92773c): Error starting userland proxy: listen tcp 192.168.64.100:443: bind: cannot assign requested address.
 * dns
docker: Error response from daemon: driver failed programming external connectivity on endpoint docksal-dns (ffa5997c24c09248e21886f170a6a437722d36afc6c91616b124c18a257315e7): Error starting userland proxy: listen udp 192.168.64.100:53: bind: cannot assign requested address.
Enabling automatic *.docksal DNS resolver...
 * ssh-agent
---------------------
COMPOSE_PROJECT_NAME_SAFE: projectA
COMPOSE_FILE:
/home/svict4/.docksal/stacks/volumes-bind.yml
/home/svict4/.docksal/stacks/stack-default.yml
/c/Users/email/Desktop/coding_projects/projectA/.docksal/docksal.yml
ENV_FILE:
/c/Users/email/Desktop/coding_projects/projectA/.docksal/docksal.env

PROJECT_ROOT: /c/Users/email/Desktop/coding_projects/projectA
DOCROOT: docroot
VIRTUAL_HOST: projectA.docksal
VIRTUAL_HOST_ALIASES: *.projectA.docksal
IP: 192.168.64.100
MYSQL:

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      DOCROOT: docroot
      HOST_GID: '1000'
      HOST_UID: '1000'
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      VIRTUAL_HOST: projectA.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:2.1-php5.6
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - /home/docker
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.1-mysql-5.6
    ports:
    - 0:3306/tcp
    volumes:
    - /c/Users/email/Desktop/coding_projects/projectA/db:/docker-entrypoint-initdb.d:ro
    - project_root:/var/www:ro,nocopy
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.project-root: /c/Users/email/Desktop/coding_projects/projectA
      io.docksal.virtual-host: projectA.docksal,*.projectA.docksal
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /c/Users/email/Desktop/coding_projects/projectA
      o: bind
      type: none

---------------------
```

</details>

<details>
  <summary>fin sysinfo output</summary>

  ```
svict4@DESKTOP-4UL0CBL:/mnt/c/Users/email/Desktop/coding_projects/projectA$ fin sysinfo
███  OS
WSL Ubuntu 16.04
Linux DESKTOP-4UL0CBL 4.4.0-17134-Microsoft #48-Microsoft Fri Apr 27 18:06:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
Mode: VirtualBox VM

███  FIN
fin version: 1.60.0

███  ENVIRONMENT
DOCKER_HOST             | 0.0.0.0:2375
 WARNING:  Non-default DOCKER_HOST

███  DOCKER
EXPECTED VERSION: 18.03.1-ce

Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: true

███  DOCKER INFO
Containers: 9
 Running: 1
 Paused: 0
 Stopped: 8
Images: 12
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.87-linuxkit-aufs
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: linuxkit-00155d580103
ID: IW77:NNLK:D2P5:7A4C:IJFN:B6H6:V2IP:3VST:ZZB6:I5CJ:ZLMI:WATB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 29
 Goroutines: 52
 System Time: 2018-06-07T01:47:31.4523224Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

███  DOCKER COMPOSE
EXPECTED VERSION: 1.21.1
docker-compose version 1.21.1, build 5a3f1a3
docker-py version: 3.3.0
CPython version: 3.6.5
OpenSSL version: OpenSSL 1.0.1t  3 May 2016

███  DOCKER: IMAGES
REPOSITORY                     TAG                 IMAGE ID            CREATED             SIZE
docksal/cli                    2.1-php7.2          80320da88f6a        2 months ago        876MB
docksal/cli                    2.1-php5.6          f3fb24308f53        2 months ago        905MB
docksal/vhost-proxy            1.2                 a1c980537985        2 months ago        166MB
openaustralia/morph-mitmdump   latest              4a247802de87        3 months ago        462MB
postgres                       9.6                 e4a66744592b        3 months ago        266MB
getfider/fider                 stable              b6d3c51aaf6b        4 months ago        18.2MB
docker4w/nsenter-dockerd       latest              cae870735e91        7 months ago        187kB
docksal/web                    2.1-apache2.4       32c1d32eba6d        9 months ago        87.5MB
docksal/db                     1.1-mysql-5.7       8d323c436c28        10 months ago       412MB
docksal/db                     1.1-mysql-5.6       6feb79af9597        10 months ago       298MB
docksal/dns                    1.0                 20c7a535479d        16 months ago       61.6MB
docksal/ssh-agent              1.0                 148220cc033d        16 months ago       12.2MB

███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                   COMMAND               CREATED             STATUS              PORTS               NAMES
9bacb638dc94        docksal/ssh-agent:1.0   "/run.sh ssh-agent"   12 seconds ago      Up 10 seconds                           docksal-ssh-agent

███  HDD Usage
docker-machine executable was not found. (Try running 'fin update')
  ```

</details>

<details>
<summary>fin system reset output</summary>

```
svict4@DESKTOP-4UL0CBL:/mnt/c/Users/email/Desktop/coding_projects/projectA$ fin system reset
Configuring network settings...
Resetting Docksal services...
 * proxy
docker: Error response from daemon: driver failed programming external connectivity on endpoint docksal-vhost-proxy (5a8a0c47127462f831f4e104a108c97aba32e92762d8e54c996d7059505de18a): Error starting userland proxy: listen tcp 192.168.64.100:443: bind: cannot assign requested address.
 * dns
docker: Error response from daemon: driver failed programming external connectivity on endpoint docksal-dns (6f20575efe043728c5d37ed7825185fa72fb19803e485ba7db847d4ec7f44f4f): Error starting userland proxy: listen udp 192.168.64.100:53: bind: cannot assign requested address.
Enabling automatic *.docksal DNS resolver...
 * ssh-agent
```

</details>

<details>

<summary>fin cleanup output</summary>

```
svict4@DESKTOP-4UL0CBL:/mnt/c/Users/email/Desktop/coding_projects/projectA$ fin cleanup
Checking for orphaned projects...
Removing dangling images...
Total reclaimed space: 0B
Removing dangling volumes...
Total reclaimed space: 0B
Removing dangling networks...
docker: Error response from daemon: driver failed programming external connectivity on endpoint docksal-vhost-proxy (9728e48e97052cc35f819c86a97d065ad5202c7ccfb3be4bf253353547c2180e): Error starting userland proxy: listen tcp 192.168.64.100:443: bind: cannot assign requested address.
```

</details>

<details>
<summary>netstat -a -n tcp output</summary>

```
svict4@DESKTOP-4UL0CBL:/mnt/c/Users/email/Desktop/coding_projects/projectA$ netstat -a -n tcp
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags       Type       State         I-Node   Path
```

</details>

<details>
<summary>fin status output</summary>

```
svict4@DESKTOP-4UL0CBL:/mnt/c/Users/email/Desktop/coding_projects/projectA$ fin status
 ALERT:  Some Docksal services were not running
         Restarting Docksal system services...
Configuring network settings...
Resetting Docksal services...
 * proxy
docker: Error response from daemon: driver failed programming external connectivity on endpoint docksal-vhost-proxy (b44a2aab920f5498b7809b1698f5804ab2d1cd9ec7c12cd488512366c6ec4684): Error starting userland proxy: listen tcp 192.168.64.100:443: bind: cannot assign requested address.
 * dns
docker: Error response from daemon: driver failed programming external connectivity on endpoint docksal-dns (778d8cfd37fbc49aa5f2c0a1f55336cf189ac58e9015a120229bcf4e487c89d3): Error starting userland proxy: listen udp 192.168.64.100:53: bind: cannot assign requested address.
Enabling automatic *.docksal DNS resolver...
 * ssh-agent
Name   Command   State   Ports
------------------------------
```

</details>

**Comment by achekulaev** [comment]
@svict4 I think you want use this advice to find which program is using port
https://stackoverflow.com/a/48199/1359178

You need to run these commands outside of WSL (i.e. in common cmd.exe) because there is something outside of WSL that is blocking those ports for you

**Comment by svict4** [comment]
@achekulaev thanks, I tried to find an application that was blocking the ports but didn't get too far, even ended up [deleting my network switches](https://support.microsoft.com/en-us/help/3101106/you-cannot-create-a-hyper-v-virtual-switch-on-64-bit-versions-of-windo).
Eventually what I ended up dating was to update `fin` manually to `1.62.2`, then did a `fin system reset` and suddenly I wasn't getting any errors!

**Comment by achekulaev** [comment]
@svict4 if you have other virtual machines (Vagrant etc.) chances are one of them was blocking those ports.

**Comment by loopy3025** [comment]
The process that my computer is using on port 80 cannot be stopped. This needs to be maintained. Is there any way I can tell Docker to use a different port?

**Comment by loopy3025** [comment]
I see there's a port mapping for MySQL but I'm having trouble finding one for apache/web in the documentation. Would this be located in the Apache settings themselves rather than the Docksal yml file?

![image](https://user-images.githubusercontent.com/6729935/41599505-691ff5a0-73a1-11e8-904a-afeffb57e3be.png)

**Comment by loopy3025** [comment]
I added this to the yml file and the site built, but it's not displaying in the browser. I'll keep playing with it.

![capture33](https://user-images.githubusercontent.com/6729935/41600140-1188e944-73a3-11e8-8c5f-31f53b1d1631.PNG)

![capture44](https://user-images.githubusercontent.com/6729935/41600145-134a2130-73a3-11e8-8920-fc3efb03bbc1.PNG)

![capture59](https://user-images.githubusercontent.com/6729935/41600203-3de617e6-73a3-11e8-91f8-4c73f81c507f.PNG)

**Comment by loopy3025** [comment]
Hmmm. I tried using 8080 explicitly and it refused. Am I missing a step for routing my site to 8080 on the browser?

![image](https://user-images.githubusercontent.com/6729935/41600968-34193cc8-73a5-11e8-8573-0e9bd67c8420.png)

**Comment by loopy3025** [comment]
I think that worked, @achekulaev . Thank you. I'm no longer getting the proxy settings error on the command line and the error in the browser has changed to "cannot provide a secure connection". I'll investigate that issue separately. Thanks!

**Comment by loopy3025** [comment]
Yep. Works fine for an HTTP site. I just have to remember how I got HTTPS to work last time. Thanks again.

![image](https://user-images.githubusercontent.com/6729935/41608272-1e618dc0-73b6-11e8-9e41-5dc2f6b399d6.png)

**Comment by loopy3025** [comment]
Never mind. Duh. I had to put :8443 in the URL instead of 8080

**Comment by achekulaev** [comment]
The root cause of binding issues on Linux was that non-Ubuntu Linux detection was not working properly hence network setup was not happening properly. Easy to check with `ip add list lo`. It should have `192.168.64.100` address bound. 

This should be fixed in the upcoming change https://github.com/docksal/docksal/issues/613

**Comment by achekulaev** [comment]
@softeg Ubuntu 18.04 is not fully supported in 1.9.0 and will be fully supported in next release, Docksal 1.10.0. If you want to use it now, you will have to update to the develop version of the software

```
DOCKSAL_VERSION=develop fin update
```

**Comment by jienckebd** [comment]
I think there's still an issue here, at least when using docker-machine / VirtualBox.

In the fin executable at /usr/local/bin/fin, the IP address of the docker VM is hardcoded to 192.168.64.100. But if you re-create the machine, the last segment of the IP increments each time.

So I was on 192.168.64.104 and /usr/local/bin/fin was still pointing at 192.168.64.100. Changing line 170 of /usr/local/bin/fin to use IP address 192.168.64.104 fixed it for me:

```
export DOCKSAL_IP="192.168.64.104"
```

**Comment by lmakarov** [comment]
@jienckebd what command where you using to recreate the VM?

**Comment by jienckebd** [comment]
I may have used `docker-machine rm docksal` at some point, but `fin vm start` wasn't working at the point I was getting this error.

I think changing line 170 of /usr/local/bin/fin to the below would work for all scenarios:

```
DOCKER_NATIVE="${DOCKER_NATIVE:-0}"

if [[ "$DOCKER_NATIVE" ]]; then
  export DOCKSAL_IP="192.168.64.100"
else
  export DOCKSAL_IP=$(docker-machine ip docksal)
fi
```

**Comment by achekulaev** [comment]
It will not work. IP has to be 64.100 or many things will not work

**Comment by begrafx** [comment]
"Out of the box", will Docksal not "cohabitate" with a running MAMP environment? I was doing a complete fresh start, only having entered, "fin vm start", everything seemed to be starting smoothly... here's what I saw:

[MyMachineName & etc.]$ fin vm start
Creating docker machine 'docksal'...
Running pre-create checks...
Creating machine...
(docksal) Downloading /Users/brianeller/.docker/machine/cache/boot2docker.iso from https://github.com/boot2docker/boot2docker/releases/download/v18.06.1-ce/boot2docker.iso...
(docksal) 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
(docksal) Creating VirtualBox VM...
(docksal) Creating SSH key...
(docksal) Starting the VM...
(docksal) Check network to re-create if needed...
(docksal) Waiting for an IP...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with boot2docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
Docker is up and running!
To see how to connect your Docker Client to the Docker Engine running on this virtual machine, run: docker-machine env docksal
docksal is already active
Pulling Docksal system images...
1.4: Pulling from docksal/vhost-proxy
4fe2ade4980c: Pull complete 
ff20d15c40a2: Pull complete 
41b8fc3e2d67: Pull complete 
3d3b6759e20f: Pull complete 
89b3cb286ebe: Pull complete 
17ee797c7442: Pull complete 
e74b9bcafccc: Pull complete 
e26efdfb8f40: Pull complete 
2f33487680ce: Pull complete 
0c33f5412ea8: Pull complete 
ee4c00914cce: Pull complete 
9f45e258d288: Pull complete 
2ee18ddcef99: Pull complete 
9bfbf64c2517: Pull complete 
08377ca8834a: Pull complete 
11d1c6bf3389: Pull complete 
9ea7dc84757f: Pull complete 
a0cc48cee8c1: Pull complete 
a59ace4c395a: Pull complete 
Digest: sha256:61fc965b82e9742ccca32e1a354e95dfc6ae6d18bc5781942c04612a1a91ac1c
Status: Downloaded newer image for docksal/vhost-proxy:1.4
1.1: Pulling from docksal/dns
4fe2ade4980c: Already exists 
63c7502e2c8c: Pull complete 
7da152633f52: Pull complete 
21d395233730: Pull complete 
55306e7ed7ac: Pull complete 
Digest: sha256:a43f0e5ad2a583a8736ec29a5cc39ecc3ccf7694488a8f2074668e18a47716c0
Status: Downloaded newer image for docksal/dns:1.1
1.2: Pulling from docksal/ssh-agent
4fe2ade4980c: Already exists 
b20e524c314b: Pull complete 
4296e8677eeb: Pull complete 
768ecc9e6d0d: Pull complete 
Digest: sha256:bf34737aac63dd2b8cc6e741ec62943d1888887838edaeb5a5dd5870cf89cb55
Status: Downloaded newer image for docksal/ssh-agent:1.2
Restoring network settings...
Resetting Docksal services...
 ➔ proxy
docker: Error response from daemon: driver failed programming external connectivity on endpoint docksal-vhost-proxy (096570f356858aacf2d9d26a7970483a3154b75910b2cc8c8c42058543fd690a): Error starting userland proxy: listen tcp 192.168.64.100:443: bind: cannot assign requested address.
 ERROR:  Failed starting the proxy service.



I did have the MAMP servers running at this time. I'm not sure if that would be an issue relating to this?

**Comment by begrafx** [comment]
To answer my own question, it doesn't appear to make any difference. I stopped the MAMP servers, cleaned up the Docksal, and ran the same command... and got the same result. So where should I go from here?

**Comment by achekulaev** [comment]
Can you show output of `nc -zv 192.168.64.100 443` ?

**Comment by achekulaev** [comment]
And also output of `ifconfig lo0`

**Comment by begrafx** [comment]
Here's what I get:

[MyMachine Name & Etc]$ nc -zv 192.168.64.100 443
nc: connectx to 192.168.64.100 port 443 (tcp) failed: Operation timed out
[MyMachine Name & Etc]$ ifconfig lo0
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=1203<RXCSUM,TXCSUM,TXSTATUS,SW_TIMESTAMP>
	inet 127.0.0.1 netmask 0xff000000 
	inet6 ::1 prefixlen 128 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
	nd6 options=201<PERFORMNUD,DAD>

**Comment by achekulaev** [comment]
You don't have Docksal IP assigned to you lo0 interface. I am not sure how you got to this, but now you need to run `fin system start`.

**Comment by begrafx** [comment]
OK, after some other research, and before your response, I decided to try "the basics", since I had previously used DrupalVM with that Virtualbox setup, and I'd seen an error that made me question if this was an issue, so I completely uninstalled Docksal and Virtualbox, and start from square one. I was able to get past that. NOW, What I'm encountering is:

<{ install data from above clipped for brevity }>
4296e8677eeb: Pull complete 
768ecc9e6d0d: Pull complete 
Digest: sha256:bf34737aac63dd2b8cc6e741ec62943d1888887838edaeb5a5dd5870cf89cb55
Status: Downloaded newer image for docksal/ssh-agent:1.2
Restoring network settings...
Resetting Docksal services...
 ➔ proxy
 ➔ dns
   upstream 192.168.1.1
Enabling automatic *.docksal DNS resolver...
Clearing DNS cache...
 ➔ ssh-agent
Identity added: id_rsa (ME@My-MacBook-Pro.local)
Configuring NFS shares...

ERROR: Attempt to share /Users via NFS would create a conflict in /etc/exports.
       To solve the problem you can override the default Docksal projects folder.
       by setting DOCKSAL_NFS_PATH value in /Users/{me}/.docksal/docksal.env.

Attempting auto-fix:
Do you want to use /Users/{me}/Projects as Docksal projects path? [y/n]: y
 ERROR:  exports:2: path contains non-directory or non-existent components: /Users/{me}/Downloads/drupal-vm
exports:2: no usable directories in export entry and no fallback
-----------------
# VAGRANT-BEGIN: 501 106b0529-5d30-42f5-ace2-7af7f48b27df
"/Users/{me}/Downloads/drupal-vm" 192.168.88.88 -alldirs -mapall=501:20
# VAGRANT-END: 501 106b0529-5d30-42f5-ace2-7af7f48b27df
# <ds-nfs docksal
/Users/{me}/Projects 127.0.0.1 192.168.64.100 -alldirs -maproot=0:0
# ds-nfs>
-----------------

I have looked and there is no "/Downloads/drupal-vm" folder; not sure where that is coming from. As you can see, answering "y" to that question yields only further error, and answering "n" simply exits the process. I've reviewed the "Troubleshooting" page, and there is no mention of this situation.

**Comment by achekulaev** [comment]
@begrafx since this is a very different issue please create a separate ticket and please use triple ticks to post the code because its unreadable.

    ```
    code here
    ```

**Comment by begrafx** [comment]
I understand. I added this in here for continuity. I'll create a separate issue.

**Comment by helro154** [comment]
I too am getting this issue. i've tried all of the steps listed here yet no results. my projects were working earlier, yet after my mac being in sleep mode it started.

**Comment by achekulaev** [comment]
@helro154 reboot your mac

**Comment by charginghawk** [comment]
Getting this error after update to the latest Docker for Mac:

```
docker: Error response from daemon: driver failed programming external connectivity on endpoint docksal-dns (9c10551adf1e79108de7083fcb3b86b94a5245b5a725227da2d660155e1a8196): Error starting userland proxy: listen udp 192.168.64.100:53: bind: cannot assign requested address.
```

Solved by downgrading Docker for Mac to 2.10.4:

https://docs.docker.com/docker-for-mac/release-notes/
https://download.docker.com/mac/stable/39773/Docker.dmg

**Comment by nnabros** [comment]
> Getting this error after update to the latest Docker for Mac (2.2.0.0):
> 
> ```
> docker: Error response from daemon: driver failed programming external connectivity on endpoint docksal-dns (9c10551adf1e79108de7083fcb3b86b94a5245b5a725227da2d660155e1a8196): Error starting userland proxy: listen udp 192.168.64.100:53: bind: cannot assign requested address.
> ```
> 
> Solved by downgrading Docker for Mac to 2.10.4:
> 
> https://docs.docker.com/docker-for-mac/release-notes/
> https://download.docker.com/mac/stable/39773/Docker.dmg

Yep. Thanks for this. I just had to downgrade to solve this error.

**Comment by lmakarov** [comment]
We a tracking the status for the 2.2.0.0 Docker Desktop version issues (both Mac and Windows) in  https://github.com/docksal/docksal/issues/1268

**Comment by sreenivasbttv** [comment]
> @svict4 if you have other virtual machines (Vagrant etc.) chances are one of them was blocking those ports.

It seems in my case happening the same. But after running **vagrant halt** command no service running on 80 and 443 ports. 
Still, I am unable to start Docksal using fin system start and not able to update using **fin update** 

<img width="1141" alt="Screenshot 2020-02-20 at 12 20 55 AM" src="https://user-images.githubusercontent.com/2751681/74904327-9ae21700-53d1-11ea-9407-91da3110dbd1.png">

**Comment by loopy3025** [comment]
We were working without error on our Macs for a very long time. After upgrading recently, we had to dial ours all the way back down to 2.0.0.3 in order to get it to work again. The DNS was just SO MAD.

**Comment by laurelstreng** [comment]
I also had to downgrade – thanks for the fix @charginghawk

**Comment by willykaram** [comment]
@lmakarov I've submitted a PR to update docksal.io

Currently the site links to Docker v2.1.0.3 for install. However, if you install that version of Docker, then the subsequent Docksal install requires the user to update Docker. 

However, the Docker install doesn't update to v2.1.0.4 (which is what Docksal needs), and instead updates to the latest version of Docker which causes the issues raised in this thread.

I'm guessing that updating Docksal.io will eliminate some of the issues people are encountering due to the above.

I've opened an issue:

https://github.com/docksal/docksal.io/issues/20

and a related PR: 

https://github.com/docksal/docksal.io/pull/21

aterials should also likely be updated:

https://docs.docksal.io/getting-started/setup/

Also note that that thread above refers to:

 Docker for Mac to 2.10.4, but it should be referring to 2.1.0.4 (i.e., the decimal is missing).
